# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='virtual',
            field=models.BooleanField(default=False, help_text='Non-physical product, does not require shipping.'),
        ),
    ]
