# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20160925_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
