# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20160925_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
