# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160925_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Markdown formatting accepted.'),
        ),
    ]
