# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
